### ISSUE TITLE
Suggestion before approx October: what will we make?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2019#1]
What will we make this year?

Submit your suggestions here. We'll vote on the suggestions in approx October 2019.

**Comment by RafayelGardishyan** [comment]
# OpenTGL
OpenTGL is what it's name says: an Open (source) Terminal Graphics Library.
With this library we can create (3d) graphics in the terminal/console and use it for further projects.
Also it's good to make Python bindings so that we can call the low level API from the high level Python.
And this will be the first step in creating CLGE -> Command Line Game Engine: A game engine which will help us to create games for Terminal/Command line

**Comment by RafayelGardishyan** [comment]
# Web App
Not only PC software is fun to make but also software for servers, and to be preciously a Web Application like a blog but also a real time online multiplayer game. Here for we can use many languages but the most used ones in web development are: Python, PHP, Java & C# (+ .NET)
I also have much experience in web development, mostly with a Python framework called Django and Flask

**Comment by RafayelGardishyan** [comment]
# Android app
Also a good idea is to make an Android app. It can be everything and programmed in languages like Java but also with some magic in HTML/CSS/JS (exmpl.: Apache Cordova).
I think this is a good idea because now almost everyone has a smartphone so we could get very popular

**Comment by Joshua260403** [comment]
# NO

**Comment by DynCoder** [comment]
# Continue with nature zen part time
We could continue with nature zen but with the option of working on your own project if you want to.

**Comment by RafayelGardishyan** [comment]
# Unity Game
Make a game in Unity Engine with C# and also make our own graphics, which is very cool I think

**Comment by DynCoder** [comment]
# Discord Bots
We split up into multiple sub-teams each making their own discord bot.
Discord API officially supports Python and Javascript, but there are tools to do it in C++.

**Comment by DynCoder** [comment]
# 2D minecraft
This one speaks for itself

**Comment by DynCoder** [comment]
# Tank Battle
cus I like tanks.
2D bird view, free roam
We could use the network part of SFML or steam SDK.
Don't worry about tank knowledge, I know enough about tanks.

**Comment by DynCoder** [comment]
# War strategy game
max ~5 players fight eachother.
Players deploy assault teams to capture eachothers towns, factories and airfields
ATs can be equiped with weapons and different soldier types.
Uses SFML network / steam SDK for matchmaking

**Comment by DynCoder** [comment]
# Tycoon
You earn money by buying stuff

**Comment by DynCoder** [comment]
I think the voting has to be in multiple rounds and multiple ways juding by the amount of suggestions

**Comment by DynCoder** [comment]
# Own project
But you could team up in subteams ofc

**Comment by DynCoder** [comment]
# DnD open world adventure game
Open world (not 2D bird view though)
Works like a text adventure but it uses graphics

**Comment by Joshua260403** [comment]
# DnD like adventure card game
You get multiple options in different scenarios
(basicly the idea above but not with a character that can move around but cards you can choose instead)
(ofc cards arent the only actions)

**Comment by DynCoder** [comment]
# Skyrim DnD crossover episode
Same's idea
The idea above but 2D bird view

**Comment by DynCoder** [comment]
# a telltale games game
#### but its not telltale its octane

**Comment by DynCoder** [comment]
Rafayel isn't really contributing any games or apps so i guess this is a ("win "*(me.n_comments-2)).pop_back() for me

**Comment by Joshua260403** [comment]
## Closed source?
Yes pls closed source so we can sell the game for ~10 cents or something

**Comment by richelbilderbeek** [comment]
Making a real-time strategy game (like [Globulation 2](https://github.com/richelbilderbeek/globulation2), StarCraft 2) in which the player has to program the units. The player has to upgrade the units' brain size to be able to let the units respond smarter.

**Comment by richelbilderbeek** [comment]
Picking any open-source game and develop a new superior AI for it to be used in online games, e.g. for [Globulation 2](https://github.com/richelbilderbeek/globulation2) or [The Battle For Wesnoth](https://github.com/wesnoth/wesnoth), like Google AlphaGo/AlphaStar did.

**Comment by richelbilderbeek** [comment]
Votes are in: a 2D tank game!
